nodeLinker: pnp

packageExtensions:
  "@mdx-js/react@^1.6.22":
    dependencies:
      react: ^17.0.0
  babel-loader@8.2.3:
    dependencies:
      webpack: ^2
  eslint-config-airbnb-base@^14.2.1:
    dependencies:
      eslint: ^7.2.0
      eslint-plugin-import: ^2.22.1
  fork-ts-checker-webpack-plugin@4.1.6:
    dependencies:
      typescript: ^2.7
      webpack: ^4

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
