name: Deploy Package

on:
  push:
    branches:
      - main

jobs:
  deploy-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - name: 'npm deploy'
        run: yarn
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
